In [31]:
import torch

In [32]:
t = torch.tensor([4])

In [33]:
t.dtype

torch.int64

In [34]:
t1 = torch.tensor([4.])

In [35]:
t1.dtype

torch.float32

In [36]:
t3 = torch.tensor([[1,2,3],[2,3,4]])

In [37]:
t3.shape

torch.Size([2, 3])

In [38]:
t3

tensor([[1, 2, 3],
        [2, 3, 4]])

In [39]:
w = torch.tensor(4., requires_grad= True)
x = torch.tensor(3., requires_grad= True)
b = torch.tensor(1.)

In [40]:
y = w*x + b

In [41]:
y.backward()

In [42]:
print("dy/dx", x.grad)

dy/dx tensor(4.)


In [43]:
print("dy/db", b.grad)

dy/db None


In [44]:
print("dy/dw", w.grad)

dy/dw tensor(3.)


In [45]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

In [46]:
torch.tensor(arr)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [47]:
torch.from_numpy(arr)

tensor([[1, 2, 3],
        [4, 5, 6]])

### Model from scratch using Pytorch

In [48]:
# inputs temp, rainfall, humidity
inputs = np.array([
                   [73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]
], dtype = np.float32)

In [49]:
# appales and oranges in tons
targets = np.array([
                    [56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]
], dtype = np.float32)

1- init weights and baises 

In [50]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [51]:
w = torch.randn(size=(2,3), requires_grad= True)
b = torch.randn(size = (2,), requires_grad=True)
w,b

(tensor([[-0.8565,  0.5764,  0.5124],
         [-0.6198, -0.2130,  0.5644]], requires_grad=True),
 tensor([-0.5763, -0.2074], requires_grad=True))

2- creating the model

In [52]:
y_hat = inputs @ w.T + b
y_hat

tensor([[ -2.4471, -35.4575],
        [  5.0012, -39.2352],
        [ 31.8689, -49.9422],
        [-44.1947, -51.7056],
        [ 31.5302, -23.9172]], grad_fn=<AddBackward0>)

In [53]:
def model(inputs, w,b):
  return inputs @ w.T +b

In [54]:
preds = model(inputs,w,b)
preds

tensor([[ -2.4471, -35.4575],
        [  5.0012, -39.2352],
        [ 31.8689, -49.9422],
        [-44.1947, -51.7056],
        [ 31.5302, -23.9172]], grad_fn=<AddBackward0>)

3- calculating the Loss

In [55]:
#mse
diff = targets - preds
diff_sqr = diff**2
m_sqr = torch.sum(diff_sqr)/diff_sqr.numel()
m_sqr

tensor(11882.2432, grad_fn=<DivBackward0>)

In [56]:
def mse ( targets,preds):
  diff = targets-preds
  return torch.sum(diff**2)/diff.numel()

In [57]:
loss = mse(targets,preds)
loss

tensor(11882.2432, grad_fn=<DivBackward0>)

4- calculating grads of weights and baises aftet that reseting them to zero

In [58]:
# we create gradiant of the loss function
'''loss.backward()
w.grad , b.grad'''

'loss.backward()\nw.grad , b.grad'

In [59]:
'''
w.grad.zero_()
b.grad.zero_()
w.grad,b.grad
'''

'\nw.grad.zero_()\nb.grad.zero_()\nw.grad,b.grad\n'

In [60]:
loss.backward()
with torch.no_grad():
  w-= w.grad * 1e-5
  b-= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [61]:
# new w and b
w,b

(tensor([[-0.7956,  0.6404,  0.5522],
         [-0.5092, -0.0901,  0.6392]], requires_grad=True),
 tensor([-0.5756, -0.2061], requires_grad=True))

5- training the model for several epochs

In [62]:
for _ in range(400):
  preds = model(inputs, w,b)
  loss = mse(targets,preds)
  loss.backward()
  with torch.no_grad():
    w-= w.grad * 1e-5
    b-= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
  print(loss)


tensor(8029.6992, grad_fn=<DivBackward0>)
tensor(5433.2471, grad_fn=<DivBackward0>)
tensor(3683.2603, grad_fn=<DivBackward0>)
tensor(2503.6968, grad_fn=<DivBackward0>)
tensor(1708.5385, grad_fn=<DivBackward0>)
tensor(1172.4270, grad_fn=<DivBackward0>)
tensor(810.8875, grad_fn=<DivBackward0>)
tensor(566.9930, grad_fn=<DivBackward0>)
tensor(402.3810, grad_fn=<DivBackward0>)
tensor(291.1996, grad_fn=<DivBackward0>)
tensor(216.0271, grad_fn=<DivBackward0>)
tensor(165.1241, grad_fn=<DivBackward0>)
tensor(130.5788, grad_fn=<DivBackward0>)
tensor(107.0597, grad_fn=<DivBackward0>)
tensor(90.9742, grad_fn=<DivBackward0>)
tensor(79.9010, grad_fn=<DivBackward0>)
tensor(72.2084, grad_fn=<DivBackward0>)
tensor(66.7970, grad_fn=<DivBackward0>)
tensor(62.9256, grad_fn=<DivBackward0>)
tensor(60.0949, grad_fn=<DivBackward0>)
tensor(57.9683, grad_fn=<DivBackward0>)
tensor(56.3189, grad_fn=<DivBackward0>)
tensor(54.9938, grad_fn=<DivBackward0>)
tensor(53.8900, grad_fn=<DivBackward0>)
tensor(52.9380, grad

In [63]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [64]:
inputs@w.T +b

tensor([[ 56.9538,  70.4852],
        [ 82.3573, 101.4409],
        [118.6890, 130.9217],
        [ 20.4387,  38.3019],
        [102.4444, 119.6879]], grad_fn=<AddBackward0>)

well done

### using pytorch

In [65]:
import torch
import numpy as np 

In [66]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], np.float32)

In [67]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], np.float32)

In [68]:
inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

Tensor dataset and Data loader

In [69]:
from torch.utils.data import TensorDataset

In [70]:
ds = TensorDataset(inputs,targets)

In [71]:
ds[1:5]

(tensor([[ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [72]:
from torch.utils.data import DataLoader

In [73]:
ds_batched = DataLoader(ds,5,True)

buliding model and init w and b

In [74]:
model = torch.nn.Linear(3,2 )

In [75]:
model.weight, model.bias

(Parameter containing:
 tensor([[-0.1979,  0.3769, -0.1106],
         [-0.1096,  0.5058,  0.4626]], requires_grad=True),
 Parameter containing:
 tensor([-0.1596,  0.5034], requires_grad=True))

In [76]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1979,  0.3769, -0.1106],
         [-0.1096,  0.5058,  0.4626]], requires_grad=True),
 Parameter containing:
 tensor([-0.1596,  0.5034], requires_grad=True)]

Loss

In [77]:
from torch.nn import functional as F

In [78]:
loss = F.mse_loss(model(inputs),targets)

In [79]:
loss

tensor(3121.9990, grad_fn=<MseLossBackward0>)

Optimizer

In [80]:
from torch.optim import SGD

In [83]:
opt = SGD(model.parameters(), lr= 1e-5)

train the model

In [86]:
for epoch in range(500):
  for x,y in ds_batched:
    # 1 -predict
    preds = model(x)
    # 2-calculate the loss
    loss = F.mse_loss(preds, y)
    # 3- calculate the gradiant
    loss.backward()
    #4- otimize w,b
    opt.step()
    #5- set gradiant to zero
    opt.zero_grad()
  print(f"{epoch+1}/500 loss = {loss}")

1/500 loss = 759.610107421875
2/500 loss = 335.653564453125
3/500 loss = 305.6731872558594
4/500 loss = 285.67401123046875
5/500 loss = 92.87559509277344
6/500 loss = 17.4533748626709
7/500 loss = 108.65473937988281
8/500 loss = 100.80652618408203
9/500 loss = 82.64482879638672
10/500 loss = 194.67071533203125
11/500 loss = 135.3976593017578
12/500 loss = 80.14863586425781
13/500 loss = 72.4404067993164
14/500 loss = 89.73550415039062
15/500 loss = 36.853240966796875
16/500 loss = 39.78263473510742
17/500 loss = 146.4616241455078
18/500 loss = 90.09256744384766
19/500 loss = 84.07505798339844
20/500 loss = 35.42436218261719
21/500 loss = 55.837921142578125
22/500 loss = 75.63893127441406
23/500 loss = 45.86751937866211
24/500 loss = 44.02759552001953
25/500 loss = 69.76579284667969
26/500 loss = 96.91930389404297
27/500 loss = 88.73052978515625
28/500 loss = 62.33549880981445
29/500 loss = 53.997718811035156
30/500 loss = 59.7645149230957
31/500 loss = 34.56552505493164
32/500 loss = 8

In [87]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3741,  0.8912,  0.5773],
         [-0.2749,  0.8178,  0.8208]], requires_grad=True),
 Parameter containing:
 tensor([-0.1561,  0.5038], requires_grad=True)]

In [88]:
model(inputs)

tensor([[ 57.0684,  70.5250],
        [ 81.1728,  99.9882],
        [120.2011, 133.7820],
        [ 21.3668,  38.0008],
        [ 99.9964, 117.5033],
        [ 55.8031,  69.4323],
        [ 80.8589,  99.9912],
        [120.4043, 134.3279],
        [ 22.6321,  39.0935],
        [100.9478, 118.5990],
        [ 56.7545,  70.5281],
        [ 79.9075,  98.8955],
        [120.5150, 133.7790],
        [ 20.4155,  36.9051],
        [101.2617, 118.5960]], grad_fn=<AddmmBackward0>)

In [90]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])